#Docker for development
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - MONGO_URI=mongodb://test:27017/dentistForm
      - NODE_ENV=test
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    depends_on:
      - db
    command: yarn test
    restart: always
    container_name: api

  db:
    image: mongo:4.2
    container_name: mongoDB
    restart: always
    ports:
      - '27017:27017'
