# Docker for production
# command: docker-compose -f docker-composer-prod.yml build
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
