#Docker for development
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - DB_HOST=db
      - NODE_ENV=development
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    depends_on:
      - db
    command: yarn dev
    restart: always

  db:
    image: mongo:4.2
    container_name: db
    restart: always
